### ISSUE TITLE
Firebase sdk 3.0

### ISSUE THREAD

**Issue by yawarts** [gigocabrera/MoneyLeash2#1]
Any clue on how to convert this to Firebase sdk 3.0 compatible?

I've followed that tutorial without exit: https://firebase.google.com/support/guides/firebase-web#update_your_client_version_numbered

**Comment by gigocabrera** [comment]
Looking into it...

**Comment by gigocabrera** [comment]
Converted to Firebase sdk 3.0.2

(this is still a work in progress...)
