### ISSUE TITLE
Bug on singup.html line 30

### ISSUE THREAD

**Issue by StammenKai** [gigocabrera/MoneyLeash2#8]
there is an bug in your singup.html on line 30.

` <ion-input [(ngModel)]="signup.username" name="username" type="text" #username="ngModel" required>`

With this Code you cant Singup for a new Account. 
It must changed to:

**line 30** = 
 `<ion-input [(ngModel)]="signup.email" name="email" type="email" #email="ngModel" required>`

**line 33** =

 `<p [hidden]="email.valid || submitted == false" color="danger" padding-left>`

and in the **singup.ts** on **line 17** =
` signup: {fullname?: string, email?: string, password?: string} = {};`

I hope i can help 

Kai Stammen (Germany)

**Comment by gigocabrera** [comment]
@StammenKai good catch. I made the changes you suggested and it should be working now. This is still a work in progress but let me know if you find anything else.
